[project]
site_name = "Some"
site_url = "https://some.appoutlet.dev"
site_description = "A Kotlin test data generation library that creates random instances of any Kotlin class"
site_author = "AppOutlet, Lda"
copyright = "© 2026 AppOutlet, Lda"
repo_url = "https://github.com/MessiasLima/Some"

nav = [
  "index.md",
  "getting-started.md",
  { "Configuration" = [
      "configuration/index.md" ,
      "configuration/nullable-strategy.md",
      "configuration/string-strategy.md",
      "configuration/collection-strategy.md"
    ] },
  "supported-types.md",
  "custom-factories.md" ,
  { "API Reference" = "https://some.appoutlet.dev/reference/latest/" }
]

[project.theme]
logo = "logo-icon.svg"
favicon = "logo-icon.svg"
features = [
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.top",
  "navigation.indexes",
  "search.highlight",
  "toc.follow",
]
custom_dir = "docs/overrides"

# Palette toggle for automatic mode
[[project.theme.palette]]
primary = "deep purple"
accent = "purple"
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
primary = "deep purple"
accent = "purple"
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
primary = "deep purple"
accent = "purple"
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.extra.analytics]
provider = "custom"
property = "5992afc8-9605-42dd-9b15-46eeba57c2aa"
