package dev.appoutlet.some.compat.kotlinfixture

import dev.appoutlet.some.config.SomeConfigBuilder
import dev.appoutlet.some.some

/**
 * Main compatibility generator instance for the KotlinFixture compatibility API.
 *
 * The configuration supplied to this fixture is applied to generated values and sequences. A configuration passed to
 * an individual call is applied after the fixture configuration and can override it.
 *
 * @param someConfig Some configuration applied to every value generated by [invoke] and [asSequence].
 */
class Fixture @JvmOverloads constructor(val someConfig: SomeConfigBuilder.() -> Unit = {}) {

    /**
     * Generates a value of type [T].
     *
     * When [range] is not empty, one of its values is returned. Otherwise, Some generates a value using this fixture's
     * configuration followed by [configuration].
     *
     * @param T Type of value to generate.
     * @param range Optional values to choose from before generating a value.
     * @param configuration Per-call Some configuration applied after [someConfig].
     * @return A generated value of type [T], or a value selected from [range].
     */
    inline operator fun <reified T> invoke(
        range: Iterable<T> = emptyList(),
        noinline configuration: SomeConfigBuilder.() -> Unit = {}
    ): T {
        val rangeShuffled = range.shuffled()
        return if (rangeShuffled.isNotEmpty()) {
            rangeShuffled.first()
        } else {
            some<T> {
                this.apply(someConfig)
                this.apply(configuration)
            }
        }
    }

    /**
     * Creates a sequence of values of type [T].
     *
     * The sequence applies this fixture's configuration and [configuration] independently to each generated value.
     * [SequenceStrategy.Unbounded] is lazy and continues until the consumer stops reading it.
     *
     * @param T Type of values to generate.
     * @param sequenceStrategy Controls whether the sequence is bounded or unbounded.
     * @param configuration Configuration applied after [someConfig] for every generated value.
     * @return A lazy sequence of generated values.
     */
    inline fun <reified T> asSequence(
        sequenceStrategy: SequenceStrategy = SequenceStrategy.Unbounded,
        noinline configuration: SomeConfigBuilder.() -> Unit = {}
    ): Sequence<T> {
        return sequence {
            val value = {
                some<T> {
                    this.apply(someConfig)
                    this.apply(configuration)
                }
            }

            when (sequenceStrategy) {
                is SequenceStrategy.Bounded -> {
                    repeat(times = sequenceStrategy.numberOfElements) {
                        yield(value())
                    }
                }

                SequenceStrategy.Unbounded -> {
                    while (true) {
                        yield(value())
                    }
                }
            }
        }
    }

    /**
     * Generates one value of type [T] using a one-off configuration.
     *
     * Unlike [invoke] and [asSequence], this call delegates directly to Some with [configuration].
     *
     * @param T Type of value to generate.
     * @param configuration Some configuration applied for this value.
     * @return A generated value of type [T].
     */
    @JvmOverloads
    inline fun <reified T> create(noinline configuration: SomeConfigBuilder.() -> Unit = {}): T {
        return some(configuration)
    }

    /**
     * Creates another fixture with the supplied configuration.
     *
     * The returned fixture does not inherit this fixture's configuration.
     *
     * @param configuration Configuration for the returned fixture.
     * @return A new fixture configured with [configuration].
     */
    fun new(configuration: SomeConfigBuilder.() -> Unit = {}): Fixture {
        return Fixture(configuration)
    }
}

/**
 * Creates a KotlinFixture compatibility generator.
 *
 * @param configuration Some configuration applied to values generated by the returned fixture.
 * @return A configured [Fixture].
 */
fun kotlinFixture(configuration: SomeConfigBuilder.() -> Unit = {}) =
    Fixture(configuration)
