package dev.appoutlet.some.compat.kotlinfixture

import dev.appoutlet.some.config.SomeConfigBuilder
import dev.appoutlet.some.some

/**
 * Main compatibility generator instance.
 */
class Fixture @JvmOverloads constructor(val someConfig: SomeConfigBuilder.() -> Unit = {}) {

    inline operator fun <reified T> invoke(
        range: Iterable<T> = emptyList(),
        noinline configuration: SomeConfigBuilder.() -> Unit = {}
    ): T {
        val rangeShuffled = range.shuffled()
        return if (rangeShuffled.isNotEmpty()) {
            rangeShuffled.first()
        } else {
            some<T> {
                this.apply(someConfig)
                this.apply(configuration)
            }
        }
    }

    /**
     * Create a sequence of instances of [T] with the option to override any [configuration] for all instances
     * generated by this sequence.
     */
    inline fun <reified T> asSequence(
        sequenceStrategy: SequenceStrategy = SequenceStrategy.Unbounded,
        noinline configuration: SomeConfigBuilder.() -> Unit = {}
    ): Sequence<T> {
        return sequence {
            val value = {
                some<T> {
                    this.apply(someConfig)
                    this.apply(configuration)
                }
            }

            when (sequenceStrategy) {
                is SequenceStrategy.Bounded -> {
                    repeat(times = sequenceStrategy.numberOfElements) {
                        yield(value())
                    }
                }

                SequenceStrategy.Unbounded -> {
                    while (true) {
                        yield(value())
                    }
                }
            }
        }
    }

    @JvmOverloads
    inline fun <reified T> create(noinline configuration: SomeConfigBuilder.() -> Unit = {}): T {
        return some(configuration)
    }

    fun new(configuration: SomeConfigBuilder.() -> Unit = {}): Fixture {
        return Fixture(configuration)
    }
}

fun kotlinFixture(configuration: SomeConfigBuilder.() -> Unit = {}) =
    Fixture(configuration)
