package dev.appoutlet.some.compat.kotlinfixture

import dev.appoutlet.some.some
import kotlin.reflect.KClass
import kotlin.reflect.KType
import kotlin.reflect.typeOf


/**
 * Main compatibility generator instance.
 */
class Fixture @JvmOverloads constructor(val fixtureConfiguration: Configuration = ConfigurationBuilder().build()) {
    inline operator fun <reified T : Any?> invoke(
        range: Iterable<T> = emptyList(),
        noinline configuration: ConfigurationBuilder.() -> Unit = {}
    ): T {
        val rangeShuffled = range.shuffled()
        return if (rangeShuffled.isNotEmpty()) {
            rangeShuffled.first()
        } else {
            val currentConfiguration = ConfigurationBuilder(fixtureConfiguration)
                .apply(configuration)
                .build()

            some<T> { parseConfiguration(currentConfiguration, this@Fixture) }
        }
    }

    /**
     * Create a sequence of instances of [T] with the option to override any [configuration] for all instances
     * generated by this sequence.
     */
    inline fun <reified T : Any?> asSequence(
        noinline configuration: ConfigurationBuilder.() -> Unit = {}
    ): Sequence<T> {
        val type = typeOf<T>()
        val builtConfiguration = ConfigurationBuilder(fixtureConfiguration).apply(configuration).build()
        return sequence {
            while (true) {
                @Suppress("DEPRECATION_ERROR")
                yield(create(type, builtConfiguration) as T)
            }
        }
    }

    /**
     * Create an instance of [clazz] with the option to override any [configuration] specifically for this instance.
     */
    @JvmOverloads
    fun create(clazz: Class<*>, configuration: Configuration = fixtureConfiguration): Any? {
        @Suppress("DEPRECATION_ERROR")
        return create(clazz.kotlin, configuration)
    }

    @Deprecated("Use the fixture<Class>() function", level = DeprecationLevel.ERROR)
    fun create(clazz: KClass<*>, configuration: Configuration = fixtureConfiguration): Any? {
        @Suppress("DEPRECATION_ERROR")
        return create(clazz.starProjectedType, configuration)
    }

    @Deprecated("Use the fixture<Class>() function", level = DeprecationLevel.ERROR)
    fun create(type: KType, configuration: Configuration = fixtureConfiguration): Any? {
        val result = ContextImpl(configuration).resolve(type)
        if (result is Unresolved) {
            throw UnsupportedOperationException("Unable to handle $type\n$result")
        }
        return result
    }

    /**
     * Generate a new [Fixture] with overridden configuration.
     */
    fun new(configuration: ConfigurationBuilder.() -> Unit = {}): Fixture {
        return Fixture(ConfigurationBuilder(fixtureConfiguration).apply(configuration).build())
    }
}

/**
 * Create a [Fixture] with [configuration]
 */
fun kotlinFixture(configuration: ConfigurationBuilder.() -> Unit = {}) =
    Fixture(ConfigurationBuilder().apply(configuration).build())