package dev.appoutlet.some.compat.kotlinfixture

/**
 * Strategy controlling the length of sequences generated by [Fixture.asSequence].
 */
sealed interface SequenceStrategy {
    /**
     * Generates values until the consumer stops reading the sequence.
     */
    data object Unbounded : SequenceStrategy

    /**
     * Generates exactly [numberOfElements] values.
     *
     * @property numberOfElements Number of values to generate. Must be non-negative.
     */
    data class Bounded(val numberOfElements: Int) : SequenceStrategy {
        init {
            require(numberOfElements >= 0) { "numberOfElements must be >= 0" }
        }
    }
}
